# Generated by Django 5.0.10 on 2025-04-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, unique=True)),
                ('ig', models.CharField(blank=True, max_length=255, null=True)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('customer_group_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'account_list',
            },
        ),
        migrations.CreateModel(
            name='delivery_unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, unique=True)),
                ('du_code', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'delivery_unit',
            },
        ),
        migrations.CreateModel(
            name='pph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ps_no', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('uan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pph',
            },
        ),
        migrations.CreateModel(
            name='sales_lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ps_no', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('uan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sales_lead',
            },
        ),
        migrations.CreateModel(
            name='sbu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'sbu',
            },
        ),
        migrations.AddField(
            model_name='opportunitytracker',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modtest.account_list'),
        ),
        migrations.AddField(
            model_name='account_list',
            name='delivery_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modtest.delivery_unit'),
        ),
        migrations.CreateModel(
            name='du_pph_rel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('du_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modtest.delivery_unit')),
                ('pph_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modtest.pph')),
            ],
            options={
                'db_table': 'du_pph_rel',
            },
        ),
        migrations.AddField(
            model_name='delivery_unit',
            name='pph',
            field=models.ManyToManyField(through='modtest.du_pph_rel', to='modtest.pph'),
        ),
        migrations.AddField(
            model_name='account_list',
            name='sbu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modtest.sbu'),
        ),
        migrations.CreateModel(
            name='sbu_sales_lead_rel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_lead_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modtest.sales_lead')),
                ('sbu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modtest.sbu')),
            ],
            options={
                'db_table': 'sbu_sales_lead_rel',
            },
        ),
        migrations.AddField(
            model_name='sbu',
            name='sales_lead',
            field=models.ManyToManyField(through='modtest.sbu_sales_lead_rel', to='modtest.sales_lead'),
        ),
    ]
