# Generated by Django 5.0.10 on 2025-04-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtest', '0002_account_list_delivery_unit_pph_sales_lead_sbu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitytracker',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_opp', to='modtest.opportunitytracker'),
        ),
    ]
