// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelTracKer.Data;


#nullable disable

namespace ModelTracKer.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20250517115928_Accelerator Migration Many To Many")]
    partial class AcceleratorMigrationManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelTracKer.Models.Accelerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("acclerator");
                });

            modelBuilder.Entity("ModelTracKer.Models.Tracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("tracker");
                });

            modelBuilder.Entity("ModelTracKer.Models.opp_Accelerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcceleratorId")
                        .HasColumnType("int");

                    b.Property<int>("TrackerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcceleratorId");

                    b.HasIndex("TrackerId");

                    b.ToTable("opp_accelerator");
                });

            modelBuilder.Entity("ModelTracKer.Models.opp_Accelerator", b =>
                {
                    b.HasOne("ModelTracKer.Models.Accelerator", "Accelerators")
                        .WithMany("OppAccelerators")
                        .HasForeignKey("AcceleratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTracKer.Models.Tracker", "Trackers")
                        .WithMany("OppAccelerators")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accelerators");

                    b.Navigation("Trackers");
                });

            modelBuilder.Entity("ModelTracKer.Models.Accelerator", b =>
                {
                    b.Navigation("OppAccelerators");
                });

            modelBuilder.Entity("ModelTracKer.Models.Tracker", b =>
                {
                    b.Navigation("OppAccelerators");
                });
#pragma warning restore 612, 618
        }
    }
}
