// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelTracKer.Data;


#nullable disable

namespace ModelTracKer.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20250519131933_ManyToManyField acc, mic, comp")]
    partial class ManyToManyFieldaccmiccomp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelTracKer.Models.Accelerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("acclerator");
                });

            modelBuilder.Entity("ModelTracKer.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("competition");
                });

            modelBuilder.Entity("ModelTracKer.Models.MicroService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("microservice");
                });

            modelBuilder.Entity("ModelTracKer.Models.Tracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("tracker");
                });

            modelBuilder.Entity("ModelTracKer.Models.opp_Accelerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcceleratorId")
                        .HasColumnType("int");

                    b.Property<int>("TrackerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcceleratorId");

                    b.HasIndex("TrackerId");

                    b.ToTable("opp_accelerator");
                });

            modelBuilder.Entity("ModelTracKer.Models.opp_competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("competion_id")
                        .HasColumnType("int");

                    b.Property<int>("competition_id")
                        .HasColumnType("int");

                    b.Property<int>("tracker_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("competion_id");

                    b.HasIndex("tracker_id");

                    b.ToTable("opp_competition");
                });

            modelBuilder.Entity("ModelTracKer.Models.opp_microservice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("microservice_id")
                        .HasColumnType("int");

                    b.Property<int>("tracker_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("microservice_id");

                    b.HasIndex("tracker_id");

                    b.ToTable("opp_microservice");
                });

            modelBuilder.Entity("ModelTracKer.Models.opp_Accelerator", b =>
                {
                    b.HasOne("ModelTracKer.Models.Accelerator", "accelerators")
                        .WithMany("OppAccelerators")
                        .HasForeignKey("AcceleratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTracKer.Models.Tracker", "trackers")
                        .WithMany("oppAccelerators")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("accelerators");

                    b.Navigation("trackers");
                });

            modelBuilder.Entity("ModelTracKer.Models.opp_competition", b =>
                {
                    b.HasOne("ModelTracKer.Models.Competition", "competition")
                        .WithMany("oppCompetitions")
                        .HasForeignKey("competion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTracKer.Models.Tracker", "tracker")
                        .WithMany("oppCompetition")
                        .HasForeignKey("tracker_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("competition");

                    b.Navigation("tracker");
                });

            modelBuilder.Entity("ModelTracKer.Models.opp_microservice", b =>
                {
                    b.HasOne("ModelTracKer.Models.MicroService", "microService")
                        .WithMany("OppMicroservice")
                        .HasForeignKey("microservice_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTracKer.Models.Tracker", "trackers")
                        .WithMany("oppMicroservices")
                        .HasForeignKey("tracker_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("microService");

                    b.Navigation("trackers");
                });

            modelBuilder.Entity("ModelTracKer.Models.Accelerator", b =>
                {
                    b.Navigation("OppAccelerators");
                });

            modelBuilder.Entity("ModelTracKer.Models.Competition", b =>
                {
                    b.Navigation("oppCompetitions");
                });

            modelBuilder.Entity("ModelTracKer.Models.MicroService", b =>
                {
                    b.Navigation("OppMicroservice");
                });

            modelBuilder.Entity("ModelTracKer.Models.Tracker", b =>
                {
                    b.Navigation("oppAccelerators");

                    b.Navigation("oppCompetition");

                    b.Navigation("oppMicroservices");
                });
#pragma warning restore 612, 618
        }
    }
}
